"""SQLAlchemy models for the clinic's dummy PostgreSQL data.

Prototype-grade on purpose: this exists so agent/tools_client.py has a
real backend to call while the voice agent is being bench-tested, not as
a production clinic management system. Swap in the real hospital DB later
without touching main.py's turn loop -- only this service's queries
change, because it speaks the exact contract voice-agent already expects.
"""
from __future__ import annotations

from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
    false,
    text,
    true,
)
from sqlalchemy.orm import declarative_base, relationship

Base = declarative_base()


class Department(Base):
    __tablename__ = "departments"
    id = Column(Integer, primary_key=True)
    name = Column(String, nullable=False, unique=True)

    doctors = relationship("Doctor", back_populates="department")


class Doctor(Base):
    __tablename__ = "doctors"
    id = Column(Integer, primary_key=True)
    name = Column(String, nullable=False)              # "Dr. S. Mukherjee" -- the short form every lookup keys on
    # The whole name ("Dr. Sourav Mukherjee"). Added by booking_migrate.add_doctor_booking_columns() on an existing DB
    # and filled by booking_migrate.backfill_doctor_full_names(); empty means "not recorded", and callers fall back to
    # `name`. The seeded given names are FICTIONAL placeholders, like every other seeded row.
    full_name = Column(String, nullable=False, default="", server_default="")
    # ...and how a Bengali or Hindi voice can SAY it: a Latin name is unspeakable there (agent/bn_normalize.py), and the
    # surname alone ("সেন") cannot tell two doctors named Sen apart when the agent must ask "which one?".
    full_name_bn = Column(String, nullable=False, default="", server_default="")
    full_name_hi = Column(String, nullable=False, default="", server_default="")
    qualifications = Column(String, nullable=False)     # "MBBS, MD (Gen. Med.)"
    # Bengali-script spellings of the surname, "|"-joined. Real callers say
    # "ডক্টর সেন", not "Dr. Sen" -- matching only the Latin name against
    # Bengali ASR output silently fails 100% of the time, not just on
    # near-misses, since the two scripts share no characters at all.
    aliases_bn = Column(String, nullable=False, default="")
    # Devanagari spellings, same reason: Hindi ASR emits Devanagari, which
    # shares no characters with either the Latin name or the Bengali alias.
    aliases_hi = Column(String, nullable=False, default="")
    department_id = Column(Integer, ForeignKey("departments.id"), nullable=False)
    # Added by booking_migrate.add_doctor_booking_columns() on an existing
    # DB -- see that module for why a real fee is needed for KCD-372.
    consultation_fee_inr = Column(Integer, nullable=False, default=500)

    department = relationship("Department", back_populates="doctors")
    schedule = relationship("DoctorSchedule", back_populates="doctor")


class DoctorSchedule(Base):
    """One row per weekday a doctor sits. A doctor with 3 chamber days has
    3 rows here, not a serialized list -- keeps the "is Dr. X in on
    Wednesday" query a plain WHERE clause."""
    __tablename__ = "doctor_schedule"
    id = Column(Integer, primary_key=True)
    doctor_id = Column(Integer, ForeignKey("doctors.id"), nullable=False)
    weekday = Column(Integer, nullable=False)   # 0=Monday ... 6=Sunday (Python's convention)
    start_time = Column(String, nullable=False)  # "18:00"
    end_time = Column(String, nullable=False)    # "20:00"

    doctor = relationship("Doctor", back_populates="schedule")

    __table_args__ = (UniqueConstraint("doctor_id", "weekday", name="uq_doctor_weekday"),)


class LabTest(Base):
    __tablename__ = "lab_tests"
    id = Column(Integer, primary_key=True)
    name = Column(String, nullable=False, unique=True)
    # Bengali-script names/synonyms a real caller would actually say,
    # "|"-joined -- see Doctor.aliases_bn for why this exists at all.
    aliases_bn = Column(String, nullable=False, default="")
    aliases_hi = Column(String, nullable=False, default="")
    rate_inr = Column(Integer, nullable=False)
    sample_type = Column(String, nullable=False)         # "Blood" / "Urine" / "Imaging" / "Cardiac"
    report_time_hours = Column(Integer, nullable=False)
    fasting_required = Column(Boolean, nullable=False, default=False)
    # Spoken-ready Bengali, same reasoning as aliases_bn: composed by
    # agent/reply_templates.py's template_prep_reply(), never generated by
    # the model -- this is Tier-3 "approved content" (Blueprint 2.2), not a
    # live numeric fact, but it still goes through a template rather than
    # being handed to the LLM, for the same reason every other fact does.
    prep_instructions_bn = Column(String, nullable=False, default="")
    prep_instructions_hi = Column(String, nullable=False, default="")
    prep_instructions_en = Column(String, nullable=False, default="")
    # Structured prep facts (KCD-381/382), added by
    # enquiry_migrate.add_enquiry_columns() on an existing DB. Kept
    # alongside the free-text prep_instructions_* above (which stay the
    # full spoken description) specifically so KCD-382's "merge to the
    # strictest constraint across several tests" is a real MAX() over
    # numbers, not string surgery on prose.
    fasting_hours = Column(Integer, nullable=True)          # null = no fasting requirement
    water_allowed_while_fasting = Column(Boolean, nullable=False, default=True)
    home_collection_eligible = Column(Boolean, nullable=False, default=True)
    prescription_required = Column(Boolean, nullable=False, default=False)
    prescription_note_bn = Column(String, nullable=False, default="")
    prescription_note_hi = Column(String, nullable=False, default="")
    prescription_note_en = Column(String, nullable=False, default="")


class FAQ(Base):
    """Deterministic answers to the questions that show up on every clinic
    line and have nothing to do with any one test or doctor -- hours,
    location, payment, insurance, parking, report collection. This is the
    Tier-3 "approved content" layer in miniature (Blueprint 2.2 / Epic
    E25): a small, explicit, hospital-approved table, matched by keyword
    the same deterministic way fast_path matches a test or doctor name,
    never composed by the model. Grows into a real retrieval store only
    when the topic count outgrows a flat table -- see fast_path.py's
    FAQCatalogue docstring for what that threshold looks like."""
    __tablename__ = "faqs"
    id = Column(Integer, primary_key=True)
    topic = Column(String, nullable=False, unique=True)   # stable key, e.g. "hours"
    # "|"-joined Bengali keyword/phrase set fast_path matches against.
    keywords_bn = Column(String, nullable=False, default="")
    # KCD-095: the same cue phrases for Hindi and English callers, so the fast path is not Bengali-only.
    keywords_hi = Column(String, nullable=False, default="")
    keywords_en = Column(String, nullable=False, default="")
    answer_bn = Column(String, nullable=False)
    answer_hi = Column(String, nullable=False, default="")
    answer_en = Column(String, nullable=False, default="")


class Appointment(Base):
    """A CONFIRMED doctor appointment. Concurrency is not guarded here --
    see SlotLock below -- so this row is only ever created once a hold on
    (doctor_id, date, time_slot) has already been won atomically.

    The uniqueness guard against double-booking the same slot is a
    PARTIAL unique index, scoped to status='confirmed' -- CodeRabbit-
    flagged, real bug: a blanket UniqueConstraint here (this table's
    original defence-in-depth design) also blocks a CANCELLED slot's row
    from ever being rebooked, since a cancelled row still occupies the
    key; a second caller who legitimately holds and confirms that freed
    slot hit an uncaught IntegrityError. booking_migrate.py's
    rebuild_appointments_partial_unique_index() moves an existing SQLite
    database from the old blanket constraint to this one (SQLite cannot
    narrow an existing UNIQUE constraint via ALTER TABLE, only by
    rebuilding the table) -- see that function's docstring."""
    __tablename__ = "appointments"
    id = Column(Integer, primary_key=True)
    confirmation_id = Column(String, nullable=False, unique=True)
    doctor_id = Column(Integer, ForeignKey("doctors.id"), nullable=False)
    date = Column(String, nullable=False)        # ISO yyyy-mm-dd
    time_slot = Column(String, nullable=False)   # "18:15"
    patient_name = Column(String, nullable=False)
    phone = Column(String, nullable=False)
    created_at = Column(DateTime, nullable=False)

    # --- booking-lifecycle columns (Epic E26) -- added by
    # booking_migrate.add_appointment_booking_columns() on an existing DB.
    patient_id = Column(Integer, ForeignKey("patients.id"), nullable=True)
    caller_phone = Column(String, nullable=True)   # who called; `phone` is the contact-for-SMS number
    status = Column(String, nullable=False, default="confirmed")  # confirmed | cancelled | rescheduled
    cancelled_at = Column(DateTime, nullable=True)
    cancellation_charge_inr = Column(Integer, nullable=True)
    rescheduled_from_id = Column(Integer, ForeignKey("appointments.id"), nullable=True)
    booking_group_id = Column(String, nullable=True)  # groups doctor+test bookings made in one call
    # KCD-488: which CancellationPolicy.version was actually applied, so a
    # later audit or dispute can see the rule in force at cancellation
    # time even after the policy itself has since been superseded -- the
    # charge alone (cancellation_charge_inr) proves an amount, not which
    # rule produced it.
    cancellation_policy_version = Column(Integer, nullable=True)

    doctor = relationship("Doctor")

    __table_args__ = (
        # CodeRabbit-flagged: sqlite_where alone only scopes the index on
        # SQLite. create_all() on PostgreSQL would otherwise create this
        # as a full (non-partial) unique index, silently letting a
        # cancelled/rescheduled appointment keep blocking a new booking
        # for the same doctor/date/time_slot. This is what a brand-new
        # database gets; an EXISTING Postgres database still needs
        # booking_migrate.py's own dialect branch to convert its already-
        # created index (see rebuild_appointments_partial_unique_index).
        Index("ux_doctor_slot_confirmed", "doctor_id", "date", "time_slot",
              unique=True,
              sqlite_where=text("status = 'confirmed'"),
              postgresql_where=text("status = 'confirmed'")),
    )


class SlotLock(Base):
    """The real concurrency guard for KCD-376: a two-caller race for the
    same doctor slot. Its own primary key IS (doctor_id, date, time_slot),
    so SQLite's single-writer file lock plus this constraint mean exactly
    one of two simultaneous INSERTs for the same key can ever succeed --
    the other gets IntegrityError, mapped to a clean "slot_taken" reply.

    A row here means "this slot is spoken for", either temporarily
    (status="held", until hold_expires_at) while a caller is still being
    walked through patient/contact details, or permanently
    (status="confirmed") once an Appointment row exists. Deleting the row
    (on cancel, on hold expiry, or when a reschedule moves off it) is what
    makes the slot bookable again -- kept in a table of its own, separate
    from `appointments`, specifically so a cancelled appointment's slot
    does not stay blocked by `appointments`' own historical UNIQUE
    constraint forever."""
    __tablename__ = "slot_locks"
    doctor_id = Column(Integer, ForeignKey("doctors.id"), primary_key=True)
    date = Column(String, primary_key=True)
    time_slot = Column(String, primary_key=True)
    status = Column(String, nullable=False)          # held | confirmed
    hold_token = Column(String, nullable=False)
    hold_expires_at = Column(DateTime, nullable=True)  # null once confirmed
    appointment_id = Column(Integer, ForeignKey("appointments.id"), nullable=True)


class Patient(Base):
    """A person an appointment or test booking is FOR -- distinct from the
    caller, who books it (KCD-364: a son booking for his mother). One
    patient can be found again across calls by phone, so a returning
    caller does not create a duplicate record every time."""
    __tablename__ = "patients"
    id = Column(Integer, primary_key=True)
    name = Column(String, nullable=False)
    phone = Column(String, nullable=False, index=True)
    age = Column(Integer, nullable=True)
    created_at = Column(DateTime, nullable=False)
    # KCD-084: "persists against the patient" -- only the DELIVERY MODE
    # (slower, one question at a time, echo each value), set when the caller
    # asked for it or an older-caller cue was recognised. Never an age
    # inference, a score or any audio: see agent/senior_voice.py.
    # server_default so a database built by create_all() matches one migrated by
    # booking_migrate (ALTER ... DEFAULT FALSE) for an INSERT that omits the column.
    senior_mode = Column(Boolean, nullable=False, default=False, server_default=false())


class PatientProxy(Base):
    """Records that a caller, on a specific phone number, is authorised to
    act for a patient who is not themselves -- KCD-364's "son booking for
    his mother". `verified_by` states HOW that was decided, never left
    implicit: "self" (caller's own phone matches the patient's own phone,
    no proxy needed), "relationship_stated" (caller declared a relationship
    and it was recorded -- sufficient to BOOK, not to read back an existing
    record), or "dob_confirmed" (caller additionally confirmed the
    patient's date of birth -- required before disclosing an EXISTING
    booking to a non-matching phone, see booking_service.authorize_access).
    """
    __tablename__ = "patient_proxies"
    id = Column(Integer, primary_key=True)
    patient_id = Column(Integer, ForeignKey("patients.id"), nullable=False)
    caller_phone = Column(String, nullable=False, index=True)
    relationship_label = Column(String, nullable=False)   # "self" | "son" | "daughter" | "spouse" | "parent" | "guardian" | "other"
    verified_by = Column(String, nullable=False)
    created_at = Column(DateTime, nullable=False)


class TestBooking(Base):
    """One lab test within a booking. KCD-365 books several tests in one
    call as several rows sharing one `booking_group_id` and one
    `confirmation_id`, so they are confirmed, prepped and read back
    together; KCD-374 adds a row to an existing group."""
    __tablename__ = "test_bookings"
    id = Column(Integer, primary_key=True)
    booking_group_id = Column(String, nullable=False, index=True)
    confirmation_id = Column(String, nullable=False, index=True)
    lab_test_id = Column(Integer, ForeignKey("lab_tests.id"), nullable=False)
    patient_id = Column(Integer, ForeignKey("patients.id"), nullable=True)
    patient_name = Column(String, nullable=False)
    date = Column(String, nullable=False)
    phone = Column(String, nullable=False)
    caller_phone = Column(String, nullable=True)
    status = Column(String, nullable=False, default="confirmed")  # confirmed | cancelled
    created_at = Column(DateTime, nullable=False)

    lab_test = relationship("LabTest")


class IdempotencyRecord(Base):
    """The stored answer to a write that carried an Idempotency-Key (clinic-api/idempotency.py)."""
    __tablename__ = "idempotency_records"
    id = Column(Integer, primary_key=True)
    key = Column(String, nullable=False)
    scope = Column(String, nullable=False)                 # which endpoint: the same key on two endpoints is two keys
    request_hash = Column(String, nullable=False)          # of the body, to refuse a key reused for a different request
    response_json = Column(Text, nullable=False)
    __table_args__ = (UniqueConstraint("key", "scope", name="uq_idempotency_key_scope"),)


class SmsOutbox(Base):
    """The open placeholder the user asked for: a real endpoint that
    genuinely records every confirmation/resend/cancellation notice this
    service would send, in the exact shape a real provider needs, but
    sends nothing itself -- `status` never becomes anything but "queued"
    until a provider is actually wired into
    clinic-api/notifications.py:send(). Logging here rather than silently
    no-op-ing means nothing pretends to have reached a caller's phone."""
    __tablename__ = "sms_outbox"
    id = Column(Integer, primary_key=True)
    to_phone = Column(String, nullable=False)
    template_key = Column(String, nullable=False)
    message = Column(String, nullable=False)
    status = Column(String, nullable=False, default="queued")  # queued -- see notifications.py
    related_confirmation_id = Column(String, nullable=True)
    created_at = Column(DateTime, nullable=False)


class DraftBooking(Base):
    """KCD-375: a caller whose call dropped mid-booking. Keyed by the
    calling phone number so a return call can find it; `slots_json` is
    whatever the in-progress agent.booking_flow.BookingState had captured.
    Expired drafts are simply not returned by lookup, never surfaced or
    applied without the caller re-confirming each value."""
    __tablename__ = "draft_bookings"
    id = Column(Integer, primary_key=True)
    caller_phone = Column(String, nullable=False, index=True)
    call_id = Column(String, nullable=False)
    slots_json = Column(String, nullable=False)
    updated_at = Column(DateTime, nullable=False)
    expires_at = Column(DateTime, nullable=False)


class DepartmentRoute(Base):
    """KCD-359: a clinician-approved, deterministic map from a symptom
    description to a department -- never the model's own judgement, and
    never framed as a diagnosis (see reply_templates.department_route_reply).
    """
    __tablename__ = "department_routes"
    id = Column(Integer, primary_key=True)
    department_id = Column(Integer, ForeignKey("departments.id"), nullable=False)
    keywords_bn = Column(String, nullable=False, default="")
    keywords_hi = Column(String, nullable=False, default="")
    keywords_en = Column(String, nullable=False, default="")

    department = relationship("Department")


# =============================================================================
# Epic E27: Information and Enquiry
# =============================================================================

class LabReport(Base):
    """KCD-383/384: whether a report is ready, and delivering it. No
    clinical VALUE is ever stored here -- the story is explicit that
    nothing clinical is read aloud under it -- only the fact of
    readiness, which is the only thing this file is allowed to state."""
    __tablename__ = "lab_reports"
    id = Column(Integer, primary_key=True)
    confirmation_id = Column(String, nullable=False, index=True)   # the booking this report is for
    patient_phone = Column(String, nullable=False)
    status = Column(String, nullable=False, default="pending")     # pending | ready
    ready_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, nullable=False)


class ReportDeliveryOTP(Base):
    """The verify-then-deliver gate KCD-384 requires. Same placeholder
    discipline as booking_service.queue_sms: the OTP is generated and
    logged here, never actually sent by this prototype -- see
    booking_service.queue_sms's docstring for the real send-path
    integration point this would go through."""
    __tablename__ = "report_delivery_otps"
    id = Column(Integer, primary_key=True)
    report_id = Column(Integer, ForeignKey("lab_reports.id"), nullable=False)
    phone = Column(String, nullable=False)
    otp_code = Column(String, nullable=False)
    verified = Column(Boolean, nullable=False, default=False)
    expires_at = Column(DateTime, nullable=False)
    created_at = Column(DateTime, nullable=False)


class ReportDeliveryAudit(Base):
    """Every delivery, with recipient and verification path -- KCD-384's
    explicit audit requirement."""
    __tablename__ = "report_delivery_audit"
    id = Column(Integer, primary_key=True)
    report_id = Column(Integer, ForeignKey("lab_reports.id"), nullable=False)
    recipient_phone = Column(String, nullable=False)
    verification_method = Column(String, nullable=False)   # "otp"
    link_token = Column(String, nullable=False)
    link_expires_at = Column(DateTime, nullable=False)
    delivered_at = Column(DateTime, nullable=False)


class DoctorLeave(Base):
    """KCD-385: a doctor not sitting on an otherwise-scheduled day, with
    a return date if known -- distinct from simply not having a
    DoctorSchedule row for that weekday at all."""
    __tablename__ = "doctor_leaves"
    id = Column(Integer, primary_key=True)
    doctor_id = Column(Integer, ForeignKey("doctors.id"), nullable=False)
    start_date = Column(String, nullable=False)     # ISO yyyy-mm-dd
    end_date = Column(String, nullable=False)
    return_date = Column(String, nullable=True)      # may be unknown

    doctor = relationship("Doctor")


class Package(Base):
    """KCD-380/397: a health package bundling several tests at a bundled
    price, so the comparison against booking them separately is a live
    arithmetic computation (rate_inr sum from LabTest), never a number
    the model states on its own."""
    __tablename__ = "packages"
    id = Column(Integer, primary_key=True)
    name = Column(String, nullable=False, unique=True)
    name_bn = Column(String, nullable=False, default="")
    name_hi = Column(String, nullable=False, default="")
    bundled_price_inr = Column(Integer, nullable=False)
    branch_restricted = Column(Boolean, nullable=False, default=False)


class PackageTest(Base):
    __tablename__ = "package_tests"
    id = Column(Integer, primary_key=True)
    package_id = Column(Integer, ForeignKey("packages.id"), nullable=False)
    lab_test_id = Column(Integer, ForeignKey("lab_tests.id"), nullable=False)

    package = relationship("Package")
    lab_test = relationship("LabTest")


class CancellationPolicy(Base):
    """KCD-488: cancellation charge/refund rules as VERSIONED, dated
    configuration -- never a number booking_service.py invents on the
    spot. Multiple rows may exist; the one actually applied to a given
    cancellation is whichever has the latest `effective_from` that is not
    after the moment of cancellation (booking_service.active_cancellation_
    policy). A brand-new table (Base.metadata.create_all() handles it, no
    ALTER TABLE migration needed), unlike Appointment.cancellation_
    policy_version, which records which version applied and DOES need one
    -- see booking_migrate.APPOINTMENT_BOOKING_COLUMNS."""
    __tablename__ = "cancellation_policies"
    id = Column(Integer, primary_key=True)
    version = Column(Integer, nullable=False, unique=True)
    effective_from = Column(String, nullable=False)   # ISO yyyy-mm-dd, policy in force ON and AFTER this date
    free_window_hours = Column(Integer, nullable=False)
    # Integer percent (0-100), not a float fraction -- avoids SQLite
    # storing/round-tripping a binary float for what is always a round
    # clinic-set percentage in practice, and keeps DB values human-
    # readable for whoever edits this table directly.
    charge_percent = Column(Integer, nullable=False)
    refund_eligible = Column(Boolean, nullable=False, default=True, server_default=true())


class WalkInPolicy(Base):
    """KCD-393: per-department (lab_test_id null) or per-test walk-in
    eligibility. `queue_note_*` is a clinician-set, non-live expectation
    string -- the story is explicit that the agent must never promise a
    wait time it cannot verify, so this is deliberately NOT a live queue
    count."""
    __tablename__ = "walk_in_policies"
    id = Column(Integer, primary_key=True)
    department_id = Column(Integer, ForeignKey("departments.id"), nullable=True)
    lab_test_id = Column(Integer, ForeignKey("lab_tests.id"), nullable=True)
    allowed = Column(Boolean, nullable=False, default=True)
    queue_note_bn = Column(String, nullable=False, default="")
    queue_note_hi = Column(String, nullable=False, default="")
    queue_note_en = Column(String, nullable=False, default="")


class BillingLineItem(Base):
    """KCD-389: what a patient owes. Owned by the hospital's own billing
    system, which clinic-api simulates the same way it simulates the
    rest of the hospital backend (unlike SMS or insurance, this is not a
    third-party integration) -- see clinic-api/main.py's module
    docstring for that framing."""
    __tablename__ = "billing_line_items"
    id = Column(Integer, primary_key=True)
    patient_id = Column(Integer, ForeignKey("patients.id"), nullable=False)
    confirmation_id = Column(String, nullable=True)
    description = Column(String, nullable=False)
    amount_inr = Column(Integer, nullable=False)
    status = Column(String, nullable=False, default="outstanding")   # outstanding | paid
    created_at = Column(DateTime, nullable=False)


class HomeCollectionCoverage(Base):
    """KCD-387: postal-code serviceability for home sample collection,
    a real coverage table rather than an estimate."""
    __tablename__ = "home_collection_coverage"
    id = Column(Integer, primary_key=True)
    postal_code = Column(String, nullable=False, unique=True)
    serviceable = Column(Boolean, nullable=False, default=False)
    charge_inr = Column(Integer, nullable=False, default=0)
    slot_note_bn = Column(String, nullable=False, default="")
    slot_note_hi = Column(String, nullable=False, default="")
    slot_note_en = Column(String, nullable=False, default="")


class InsurancePolicy(Base):
    """KCD-388: mock insurer-side policy records. Simulates what an
    external insurer's API would return -- this prototype has no real
    insurer integration, the same disclosed-placeholder discipline as
    booking_service.queue_sms, and insurance_service.check_coverage()'s
    docstring says so explicitly at the point a real integration would
    replace this table with an HTTP call."""
    __tablename__ = "insurance_policies"
    id = Column(Integer, primary_key=True)
    policy_number = Column(String, nullable=False, unique=True)
    insurer_name = Column(String, nullable=False)
    patient_phone = Column(String, nullable=False)
    active = Column(Boolean, nullable=False, default=True)


class InsuranceCoverageRule(Base):
    __tablename__ = "insurance_coverage_rules"
    id = Column(Integer, primary_key=True)
    insurer_name = Column(String, nullable=False)
    lab_test_id = Column(Integer, ForeignKey("lab_tests.id"), nullable=True)   # null = applies to all tests
    coverage_percent = Column(Integer, nullable=False)
    co_payment_inr = Column(Integer, nullable=False, default=0)


class CallOutcome(Base):
    """KCD-394: an out-of-scope question, captured rather than dropped --
    feeds the coverage backlog by reason code."""
    __tablename__ = "call_outcomes"
    id = Column(Integer, primary_key=True)
    call_id = Column(String, nullable=False)
    reason_code = Column(String, nullable=False, default="out_of_scope")
    caller_question = Column(String, nullable=False)
    created_at = Column(DateTime, nullable=False)


class DepartmentHours(Base):
    """KCD-386: per-department hours, overriding the clinic-wide FAQ
    "hours" entry where a department keeps different timing. Scoped to
    department only, not department-and-branch: this prototype's seed
    data (seed.py) models a single clinic with no branch concept
    anywhere else in the schema, so adding one here alone, for one
    story, would be schema surgery the rest of the system does not
    support or need yet."""
    __tablename__ = "department_hours"
    id = Column(Integer, primary_key=True)
    department_id = Column(Integer, ForeignKey("departments.id"), nullable=False, unique=True)
    hours_bn = Column(String, nullable=False)
    hours_hi = Column(String, nullable=False, default="")
    hours_en = Column(String, nullable=False, default="")
    effective_from = Column(String, nullable=True)   # ISO date, null = always in effect


class CallbackRequest(Base):
    """KCD-398: a promised callback. No real outbound-calling system
    exists (Epic E22/telephony infra) -- this records the promise and
    its fulfilment status, the placeholder half of the same discipline
    as SMS: never claim a call was placed that was not."""
    __tablename__ = "callback_requests"
    id = Column(Integer, primary_key=True)
    phone = Column(String, nullable=False)
    call_id = Column(String, nullable=False)
    requested_window = Column(String, nullable=False)
    reason = Column(String, nullable=False, default="")
    status = Column(String, nullable=False, default="scheduled")   # scheduled | fulfilled | cancelled
    created_at = Column(DateTime, nullable=False)


# =============================================================================
# Epic E33: Patient Context and History
# =============================================================================
# The voicebot must not become a competing source of truth for a patient's health
# record. What lives here is what THIS SERVICE itself created (its own calls, its own
# bookings, the patient's stated preferences) plus mirrors that a hospital connector
# (KCD-131) will keep filled; nothing here is a clinical fact the agent authored, and
# nothing here holds a result value.

class CallRecord(Base):
    """KCD-501: one row per call, written as the call goes (each completed action is
    recorded when it completes, so a call that drops still shows what was done) and
    closed at hang-up. Keyed by `call_id`; every write is an idempotent merge, so a
    retried request cannot double a record or a booking summary."""
    __tablename__ = "call_records"
    id = Column(Integer, primary_key=True)
    call_id = Column(String, nullable=False, unique=True, index=True)
    channel = Column(String, nullable=False, default="voice")          # voice | sms | whatsapp
    caller_phone = Column(String, nullable=True, index=True)
    patient_id = Column(Integer, ForeignKey("patients.id"), nullable=True)
    started_at = Column(DateTime, nullable=False)
    ended_at = Column(DateTime, nullable=True)
    languages = Column(String, nullable=False, default="")             # comma-separated, first use first
    intents_json = Column(Text, nullable=False, default="[]")
    actions_json = Column(Text, nullable=False, default="[]")          # what was DONE (booked, cancelled, ...)
    confirmed_json = Column(Text, nullable=False, default="{}")        # values the caller confirmed (redacted)
    history_statements_json = Column(Text, nullable=False, default="[]")   # KCD-500: ids of history statements rendered
    escalation_reason = Column(String, nullable=True)
    outcome = Column(String, nullable=False, default="in_progress")    # in_progress | completed | handed_off | abandoned | failed
    disclosure_version = Column(String, nullable=False, default="")
    last_seq = Column(Integer, nullable=False, default=0)              # events applied so far (idempotency)
    updated_at = Column(DateTime, nullable=False)


class HistoryAudit(Base):
    """KCD-495: every read of a patient's history, attributed to the call that made it
    -- and every REFUSED read, because an attempt is as auditable as a success."""
    __tablename__ = "history_audit"
    id = Column(Integer, primary_key=True)
    call_id = Column(String, nullable=False, index=True)
    patient_id = Column(Integer, ForeignKey("patients.id"), nullable=True)
    kind = Column(String, nullable=False)                              # timeline_read | timeline_denied | ...
    fields_json = Column(Text, nullable=False, default="[]")
    at = Column(DateTime, nullable=False)


class PatientPreference(Base):
    """KCD-499: stored against the PATIENT, not the handset. Offered for confirmation,
    never applied silently; a stored language bias never overrides what the caller
    actually says (agent/patient_context.effective_language)."""
    __tablename__ = "patient_preferences"
    id = Column(Integer, primary_key=True)
    patient_id = Column(Integer, ForeignKey("patients.id"), nullable=False, unique=True)
    branch = Column(String, nullable=True)
    collection_address = Column(String, nullable=True)
    delivery_channel = Column(String, nullable=True)                   # sms | whatsapp | voice
    accessibility_mode = Column(String, nullable=True)                 # slower | shorter | none
    language_bias = Column(String, nullable=True)                      # bn | hi | en
    updated_at = Column(DateTime, nullable=False)


class TestPerformance(Base):
    """KCD-498: THAT a test was performed and when -- never what it showed. In
    production a hospital connector (KCD-131) keeps this filled from the LIS; the
    table deliberately has no column for a result, a value or an interpretation."""
    __tablename__ = "test_performances"
    id = Column(Integer, primary_key=True)
    patient_id = Column(Integer, ForeignKey("patients.id"), nullable=False, index=True)
    lab_test_id = Column(Integer, ForeignKey("lab_tests.id"), nullable=False)
    performed_on = Column(String, nullable=False)                      # ISO date
    source = Column(String, nullable=False, default="local")
    created_at = Column(DateTime, nullable=False)


class RetestInterval(Base):
    """KCD-498: a CLINICIAN-APPROVED interval after which a test is due again. There
    is no default and no guess: a test with no row here has no "due" statement at
    all, because inventing a retest interval is giving medical advice."""
    __tablename__ = "retest_intervals"
    id = Column(Integer, primary_key=True)
    lab_test_id = Column(Integer, ForeignKey("lab_tests.id"), nullable=False, unique=True)
    interval_days = Column(Integer, nullable=False)
    approved_by = Column(String, nullable=False)
    approved_at = Column(String, nullable=False)                       # ISO date


# ================================================================================================
# Patient registry, verification, medicines, call-outcome history, one-day cache, editable
# agent messages and the audit log. Sample rows are seeded by patient_seed.py; in production the
# registry, medicines and test history are filled by the hospital connector (KCD-131).
# ================================================================================================

class PatientRegistry(Base):
    """The registry row for a patient: the facts the SECURITY QUESTIONS check against (date of birth,
    address, registered patient id) and nothing clinical. One row per `patients` row. Names and
    addresses may carry aliases in Bengali and Hindi script because that is how a caller's speech
    is transcribed; they are compared exactly (token for token), never by sound."""
    __tablename__ = "patient_registry"
    id = Column(Integer, primary_key=True)
    patient_id = Column(Integer, ForeignKey("patients.id"), nullable=False, unique=True)
    patient_uid = Column(String, nullable=False, unique=True, index=True)      # the id printed on the card, e.g. KCP-100234
    dob = Column(String, nullable=False)                                        # ISO date
    gender = Column(String, nullable=True)
    address_text = Column(String, nullable=False, default="")
    locality = Column(String, nullable=True)
    pincode = Column(String, nullable=True)
    name_aliases = Column(String, nullable=False, default="")                   # "|"-separated, other scripts
    address_aliases = Column(String, nullable=False, default="")                # "|"-separated, other scripts
    registered_on = Column(String, nullable=False)
    status = Column(String, nullable=False, default="active")                   # active | inactive | merged
    source = Column(String, nullable=False, default="local")                   # local | his


class Medicine(Base):
    """A medicine in the catalogue. Names only: there is deliberately no dosage guidance, no
    indication and no interaction data here, because the agent gives no clinical advice."""
    __tablename__ = "medicines"
    id = Column(Integer, primary_key=True)
    name = Column(String, nullable=False, unique=True)
    generic_name = Column(String, nullable=True)
    aliases_bn = Column(String, nullable=False, default="")
    aliases_hi = Column(String, nullable=False, default="")


class PatientMedicine(Base):
    """THAT a medicine was prescribed to a patient and when -- a record of a fact, mirrored from
    the hospital. No dose interpretation, no advice, no "should take"; like TestPerformance it has
    no column for one."""
    __tablename__ = "patient_medicines"
    id = Column(Integer, primary_key=True)
    patient_id = Column(Integer, ForeignKey("patients.id"), nullable=False, index=True)
    medicine_id = Column(Integer, ForeignKey("medicines.id"), nullable=False)
    prescribed_on = Column(String, nullable=False)                              # ISO date
    prescribed_by = Column(String, nullable=True)
    source = Column(String, nullable=False, default="local")
    created_at = Column(DateTime, nullable=False)
    medicine = relationship("Medicine")


class PatientHistory(Base):
    """One row per thing a CALL did for a patient, inserted when the call closes: a booking, a
    cancellation, a question answered, an escalation. It is the durable history that call outcomes
    feed; the one-day cache below is what the NEXT call is greeted with."""
    __tablename__ = "patient_history"
    id = Column(Integer, primary_key=True)
    patient_id = Column(Integer, ForeignKey("patients.id"), nullable=False, index=True)
    call_id = Column(String, nullable=False, index=True)
    kind = Column(String, nullable=False)          # booking_confirmed | tests_booked | appointment_cancelled | ... | call_outcome
    ref = Column(String, nullable=False, default="")   # confirmation id where there is one
    detail_json = Column(Text, nullable=False, default="{}")
    at = Column(DateTime, nullable=False)
    __table_args__ = (UniqueConstraint("call_id", "kind", "ref", name="uq_patient_history_once"),)


class PatientCallCache(Base):
    """KCD-496: the patient's last call, kept for ONE DAY (`expires_at`) and used as context by the
    next call. Expired rows are ignored and purged; the permanent record is PatientHistory."""
    __tablename__ = "patient_call_cache"
    id = Column(Integer, primary_key=True)
    patient_id = Column(Integer, ForeignKey("patients.id"), nullable=True, index=True)
    caller_phone = Column(String, nullable=True, index=True)
    call_id = Column(String, nullable=False, unique=True)
    summary_json = Column(Text, nullable=False, default="{}")
    created_at = Column(DateTime, nullable=False)
    expires_at = Column(DateTime, nullable=False, index=True)


class VerificationSession(Base):
    """A passed security check, held server-side for the call: the ONLY thing that authorises a
    history read. `attempts` counts evaluations, `locked` stops a brute-force of the questions."""
    __tablename__ = "verification_sessions"
    id = Column(Integer, primary_key=True)
    call_id = Column(String, nullable=False, index=True)
    patient_id = Column(Integer, ForeignKey("patients.id"), nullable=False)
    method = Column(String, nullable=False, default="security_questions")
    factors_json = Column(Text, nullable=False, default="[]")                   # which factors matched (names only)
    attempts = Column(Integer, nullable=False, default=0)
    verified_at = Column(DateTime, nullable=True)
    expires_at = Column(DateTime, nullable=True)
    locked = Column(Boolean, nullable=False, default=False, server_default=false())
    __table_args__ = (UniqueConstraint("call_id", "patient_id", name="uq_verification_call_patient"),)


class AgentMessage(Base):
    """Wording the operator can change WITHOUT a deploy: the disclosure, the "I cannot find that"
    message, the thank-you acknowledgement, and any phrase in agent/phrases.py by its key. The
    agent reads these at call start and falls back to its built-in text if the API is down, so an
    outage can never leave it silent. `version` increases on every change and is written into the
    call record, so an audit knows which wording a caller heard."""
    __tablename__ = "agent_messages"
    id = Column(Integer, primary_key=True)
    key = Column(String, nullable=False)
    lang = Column(String, nullable=False)
    text = Column(Text, nullable=False)
    version = Column(Integer, nullable=False, default=1)
    active = Column(Boolean, nullable=False, default=True, server_default=true())
    updated_at = Column(DateTime, nullable=False)
    updated_by = Column(String, nullable=True)
    __table_args__ = (UniqueConstraint("key", "lang", name="uq_agent_message_key_lang"),)


class AuditLog(Base):
    """Everything the agent did that touches a patient or a rule, one row each: identification
    attempts, security-question attempts (pass, fail, lock), history reads and refusals, booking
    actions, escalations, message edits, call closes. Attempts are as auditable as successes."""
    __tablename__ = "audit_log"
    id = Column(Integer, primary_key=True)
    at = Column(DateTime, nullable=False, index=True)
    call_id = Column(String, nullable=True, index=True)
    patient_id = Column(Integer, nullable=True, index=True)
    actor = Column(String, nullable=False, default="agent")                     # agent | operator | system
    action = Column(String, nullable=False, index=True)
    outcome = Column(String, nullable=False, default="ok")                      # ok | denied | failed | locked
    detail_json = Column(Text, nullable=False, default="{}")
