"""Report which doctors and which tests in the clinic catalogue can be mistaken for each other.

    python tools/confusable_pairs.py                        # the seeded clinic data
    python tools/confusable_pairs.py --catalogue cat.json   # a saved /api/v1/catalogue answer
    python tools/confusable_pairs.py --markdown docs/confusable-pairs-report.md

No recordings and no pod needed. It applies the SAME folding the live matcher uses (agent/gazetteer.py) to every pair of
entities, and lists the pairs where a caller's words could mean either, and the words shared by several test names.
Wherever a pair is listed, the agent must ask "which one?" instead of picking (CLAUDE.md, "Doctor Nobody"). Run it again
whenever the catalogue changes, and on the real catalogue before go-live: the seeded one here is invented.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from typing import Any

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if ROOT not in sys.path:
    sys.path.append(ROOT)

from agent.catalogue_forms import TITLES, doctor_forms, lab_test_forms  # noqa: E402
from agent.confusables import find_confusables, shared_words  # noqa: E402


def build_report(cat: dict[str, Any]) -> dict[str, Any]:
    doctors, tests = doctor_forms(cat), lab_test_forms(cat)
    report: dict[str, Any] = {}
    for label, entries in (("doctors", doctors), ("tests", tests)):
        pairs = find_confusables(entries, drop_words=TITLES)
        report[label] = {
            "entities": len({c for c, _f in entries}),
            "forms": len(entries),
            "pairs": [
                {
                    "a": p.a,
                    "b": p.b,
                    "form_a": p.form_a,
                    "form_b": p.form_b,
                    "basis": p.basis,
                    "risk": p.risk,
                    "similarity": p.similarity,
                }
                for p in pairs
            ],
            "shared_words": shared_words(entries, drop_words=TITLES if label == "doctors" else ()),
        }
    return report


def _pair_line(p: dict[str, Any]) -> str:
    return f"| {p['risk']} | {p['a']} | {p['b']} | {p['form_a']} / {p['form_b']} | {p['basis']} | {p['similarity']} |"


def render_markdown(report: dict[str, Any], source: str) -> str:
    out = [
        "# Names that can be mistaken for each other",
        "",
        f"Source: {source}. Generated by `tools/confusable_pairs.py` with the folding the live matcher uses "
        "(`agent/gazetteer.py`). **Reasoned, not measured:** it says which pairs the matcher itself finds close, "
        "not how often callers confuse them. Where a pair is listed the agent must ask which one, never pick.",
        "",
    ]
    for label in ("doctors", "tests"):
        sec = report[label]
        pairs = sec["pairs"]
        high = sum(p["risk"] == "high" for p in pairs)
        out += [
            f"## {label.title()}: {sec['entities']} entities, {sec['forms']} spoken forms",
            "",
            f"{len(pairs)} confusable pairs ({high} high risk).",
            "",
        ]
        if pairs:
            out += [
                "| risk | one | other | forms that came closest | evidence | similarity |",
                "|---|---|---|---|---|---|",
                *[_pair_line(p) for p in pairs],
                "",
            ]
        words = sec["shared_words"]
        out.append(f"Words shared by several {label} (a caller who says only this has not said which one):")
        out.append("")
        if words:
            grouped: dict[tuple[str, ...], list[str]] = {}
            for w, names in words.items():  # the same word in three scripts is one finding
                grouped.setdefault(tuple(names), []).append(w)
            out += [f"- {', '.join(f'`{w}`' for w in ws)}: {', '.join(names)}" for names, ws in grouped.items()]
        else:
            out.append("- none")
        out.append("")
    return "\n".join(out)


def _load(path: str | None) -> tuple[dict[str, Any], str]:
    if path:
        with open(path, encoding="utf-8") as f:
            return json.load(f), path
    sys.path.append(os.path.join(ROOT, "tests"))
    from _clinic_app import clinic_app  # the seeded clinic API, in its own temporary database

    with clinic_app(sample_patients=False) as (_app, client):
        return client.get("/api/v1/catalogue").json(), "the seeded clinic data (invented names)"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--catalogue", help="a saved /api/v1/catalogue JSON; default is the seeded clinic data")
    ap.add_argument("--markdown", help="write the report to this file (Markdown)")
    ap.add_argument("--json", action="store_true", help="print the report as JSON")
    args = ap.parse_args(argv)
    cat, source = _load(args.catalogue)
    report = build_report(cat)
    text = render_markdown(report, source)
    if args.markdown:
        with open(args.markdown, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
    print(json.dumps(report, ensure_ascii=False, indent=2) if args.json else text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
